###
LAYOUT
layout-grid
layout-grid--grid-story-1
layouto-grid--grid-story-2
layout-header-prelogin
layout-header-prelogin--header-story-1
layout-header-prelogin--header-story-2
layout-header-prelogin--header-story-3
layout-header-prelogin--header-story-4
layout-header-prelogin--header-story-5
layout-header-prelogin--header-story-6
layout-header-prelogin--header-story-7
layout-header-prelogin--header-story-8
layout-lightboxlayout
layout-lightboxlayout--page-lightbox-layout-story-1
layout-lightboxlayout--page-lightbox-layout-story-2
layout-lightboxlayout--page-lightbox-layout-story-3
layout-lightboxlayout--page-lightbox-layout-story-4
layout-modallayout
layout-modallayout--modal-layout-story-1
layout-modallayout--modal-layout-story-2
layout-page
layout-page--page-story-1
layout-page--page-story-2
layout-page--page-story-3
layout-page--page-story-4
layout-pagedetails
layout-pagedetails--page-details-story-1
layout-pagedetails--page-details-story-2
layout-pagedetails--page-details-story-3
layout-pagedetails--page-details-story-4
layout-pagedetails--page-details-story-5
layout-pageinnerlayout
layout-pageinnerlayout--page-inner-layout-story-1
layout-pageinnerlayout--page-inner-layout-story-2
layout-pageinnerlayout--page-inner-layout-story-3
layout-sidebar
layout-sidebar--side-bar-story-1
layout-sidebar--side-bar-story-2
###

export tag Sketch < section
	def render
		<self>