###
DATA DISPLAY
data-display-accordion
data-display-accordion--accordion-story-1
data-display-accordion--accordion-story-2
data-display-accordion--accordion-story-3
data-display-accordion--accordion-story-4
data-display-attachmentlist
data-display-attachmentlist--attachment-list-story-1
data-display-attachmentlist--attachment-list-story-2
data-display-attachmentlist--attachment-list-story-3
data-display-attachmentlist--attachment-list-story-4
data-display-badge
data-display-badge--badge-story-1
data-display-badge--badge-story-2
data-display-badge--badge-story-3
data-display-badge--badge-story-4
data-display-buttongroup
data-display-buttongroup--button-group-story-1
data-display-buttongroup--button-group-story-10
data-display-buttongroup--button-group-story-11
data-display-buttongroup--button-group-story-2
data-display-buttongroup--button-group-story-3
data-display-buttongroup--button-group-story-4
data-display-buttongroup--button-group-story-5
data-display-buttongroup--button-group-story-6
data-display-buttongroup--button-group-story-7
data-display-buttongroup--button-group-story-9
data-display-buttons
data-display-buttons--button-story-1
data-display-buttons--button-story-2
data-display-buttons--button-story-3
data-display-buttons--button-story-4
data-display-buttons--button-story-5
data-display-buttons--button-story-6
data-display-buttons--button-story-7
data-display-buttons--button-story-8
data-display-buttons--button-story-9
data-display-buttons--button-story-91
data-display-carousel
data-display-carousel--carousel-story-1
data-display-carousel--carousel-story-2
data-display-carousel--carousel-story-3
data-display-carousel--carousel-story-4
data-display-chips
data-display-chips--chips-story-1
data-display-chips--chips-story-2
data-display-chips--chips-story-3
data-display-chips--chips-story-4
data-display-chips--chips-story-5
data-display-collapsepanel
data-display-collapsepanel--collapse-panel-story-1
data-display-collapsepanel--collapse-panel-story-2
data-display-collapsepanel--collapse-panel-story-3
data-display-collapsepanel--collapse-panel-story-4
data-display-commission
data-display-commission--basic-comission-story-1
data-display-commission--showcase-2
data-display-countdown
data-display-countdown--basic
data-display-currency
data-display-currency--basic
data-display-currency--story
data-display-dialog
data-display-dialog--dialog-story-1
data-display-divider
data-display-divider--divider-story-1
data-display-divider--divider-story-2
data-display-docviewer
data-display-docviewer--doc-viewer-story-1
data-display-docviewer--doc-viewer-story-2
data-display-docviewer--doc-viewer-story-3
data-display-docviewer--doc-viewer-story-4
data-display-dropdown
data-display-dropdown--dropdown-story-1
data-display-dropdown--dropdown-story-2
data-display-dropdown--dropdown-story-3
data-display-dropdown--dropdown-story-4
data-display-dropdown--dropdown-story-5
data-display-dropdown--dropdown-story-6
data-display-dropdown--dropdown-story-7
data-display-emptyblock
data-display-emptyblock--empty-block-story-1
data-display-emptyblock--empty-block-story-2
data-display-emptyblock--empty-block-story-3
data-display-emptyblock--empty-block-story-4
data-display-formnotifications
data-display-formnotifications--form-notifications-story-1
data-display-formnotifications--form-notifications-story-2
data-display-informer
data-display-informer--informer-story-1
data-display-informer--informer-story-2
data-display-informer--informer-story-3
data-display-linenotifications
data-display-linenotifications--line-notifications-story-1
data-display-linenotifications--line-notifications-story-2
data-display-link
data-display-link--link-story-1
data-display-link--link-story-2
data-display-link--link-story-3
data-display-link--link-story-4
data-display-link--link-story-5
data-display-loadingindicator
data-display-loadingindicator--loading-indicator-story-1
data-display-loadingindicator--loading-indicator-story-2
data-display-menu
data-display-menu--menu-story-1
data-display-menu--menu-story-2
data-display-menu--menu-story-3
data-display-menu--menu-story-4
data-display-menu--menu-story-5
data-display-menu--menu-story-6
data-display-modal
data-display-modal--modal-story-1
data-display-modal--modal-story-2
data-display-overflowmenu
data-display-overflowmenu--overflow-menu-story-1
data-display-overflowmenu--overflow-menu-story-2
data-display-overflowmenu--overflow-menu-story-3
data-display-overflowmenu--overflow-menu-story-4
data-display-overlay
data-display-overlay--overlay-story-1
data-display-overlay--overlay-story-2
data-display-pagination
data-display-pagination--pagination-story-1
data-display-pagination--pagination-story-2
data-display-pagination--pagination-story-3
data-display-pagination--pagination-story-4
data-display-pagination--pagination-story-5
data-display-preloader
data-display-preloader--basic
data-display-progress
data-display-progress--progress-story-1
data-display-progress--progress-story-2
data-display-progress--progress-story-3
data-display-status
data-display-status--status-story-1
data-display-status--status-story-2
data-display-stepper
data-display-stepper--stepper-story-1
data-display-stepper--stepper-story-2
data-display-stepper--stepper-story-3
data-display-stepperaccordion
data-display-stepperaccordion--stepper-accordion-story-1
data-display-stepperaccordion--stepper-accordion-story-2
data-display-stepperaccordion--stepper-accordion-story-3
data-display-stepperaccordion--stepper-accordion-story-4
data-display-table
data-display-table--table-story-1
data-display-table--table-story-2
data-display-table--table-story-3
data-display-table--table-story-4
data-display-table--table-story-5
data-display-table--table-story-6
data-display-table--table-story-7
data-display-table--table-story-8
data-display-table--table-story-9
data-display-table--table-story-90
data-display-table--table-story-91
data-display-table--table-story-92
data-display-tabs
data-display-tabs--tabs-story-1
data-display-tabs--tabs-story-2
data-display-tabs--tabs-story-3
data-display-tabs--tabs-story-4
data-display-tabs--tabs-story-5
data-display-tag
data-display-tag--tag-story-1
data-display-tag--tag-story-2
data-display-tag--tag-story-3
data-display-timer
data-display-timer--timer-story-1
data-display-timer--timer-story-2
data-display-timer--timer-story-3
data-display-toastnotifications
data-display-toastnotifications--toast-notifications-story-1
data-display-toastnotifications--toast-notifications-story-2
data-display-tooltip
data-display-tooltip--tooltip-story-1
data-display-tooltip--tooltip-story-2
data-display-tooltip--tooltip-story-3
data-display-tree
data-display-tree--tree-story-1
data-display-tree--tree-story-2
data-display-tree--tree-story-3
###

import Sketch as DataDisplayCarousel from './data-display-carousel'

export tag Sketch < section

	@classes = []

	def render
		<self.data-display>
			<DataDisplayCarousel route="data-display-carousel">