###
CHARTS
charts-общий-раздел-charts
charts-общий-раздел-charts--charts-story-1
charts-общий-раздел-charts--charts-story-2
charts-общий-раздел-charts--charts-story-3
charts-общий-раздел-charts--charts-story-4
charts-columnchart
charts-columnchart--column-chart-1
charts-columnchart--column-chart-2
charts-columnchart--column-chart-3
charts-columnchart--column-chart-4
charts-columnchart--column-chart-5
charts-columnchart--column-chart-6
charts-columnchart--column-chart-7
charts-donutchart
charts-donutchart--donut-chart-1
charts-donutchart--donut-chart-2
charts-donutchart--donut-chart-3
charts-donutchart--donut-chart-4
charts-donutchart--donut-chart-5
charts-donutchart--donut-chart-6
charts-donutchart--donut-chart-7
charts-donutchart--donut-chart-8
charts-linechart
charts-linechart--line-chart-1
charts-linechart--line-chart-2
charts-linechart--line-chart-3
charts-linechart--line-chart-4
charts-linechart--line-chart-5
charts-linechart--line-chart-6
charts-linechart--line-chart-7
charts-linechart--line-chart-8
charts-linechart--line-chart-9
###

export tag Sketch < section
	def render
		<self>